### ISSUE TITLE
Sample Plugin Definition

### ISSUE THREAD

**Issue by AugustMiller** [benbaptist/wrapper.py#3]
Hi, Ben!

I've been using v1 of Wrapper for a couple years, and love it. I'd never really gotten into writing an extension, but I was curious if the v1 examples are more or less portable to the new design?

I realize the API is still under development, and significant changes are apt to happen, but I was hoping you'd be able to provide a sort of template or "Hello world" example for us to hack around on...

Thanks for all your work on this! :revolving_hearts:

**Comment by benbaptist** [comment]
Hey August! 

I'm glad to hear that you've been using Wrapper, that's super awesome!

The v1 examples are going to be fairly similar since I didn't really feel the need to change it too much, at least structurally. But there's definitely some bigger changes in a lot of the methods and stuff that will destroy any kind of backwards compatibilty. 

This is the little test plugin I've been using while I develop the API. Most of the current API is just stuff that I needed on the spot, and the long-term plan is to actually sit down and R&D a well thought-out AP.

https://gist.github.com/benbaptist/599ef239bd64e31d3cc953722ff22df7

Hopefully this (maybe) helps until I get proper documentation and example plguins made!

**Comment by AugustMiller** [comment]
Brilliant, this is exactly what I needed! I could see hints at the `__enable__` and `__disable__` methods via the `Plugin` class, but wasn't sure if there was some additional magic happening.

Hoping to use this as an excuse to learn Python (again?)—finding myself with a bit of free time, these days. 😅

Thanks for getting back so quick. Look forward to seeing your design unfold!

**Comment by benbaptist** [comment]
My pleasure! Yup, free time is abundent for me too - that's why I decided to make this rewrite in the first place. 😅 And for the forseeable future, I'm going to have a lot more free time to continue working on it. Hoping to get near-feature parity with the original Wrapper in the next few months!

**Comment by benbaptist** [comment]
Looks like everything is good here, so I'm going to go ahead and close this issue. Feel free to re-open if you're having any issues, or open a new one - whatever floats your boat!
